server:
  port: 8080
spring:
  application:
    name: embabel-java-agent-tutorial

embabel:
#  models:
#    default-llm: deepseek-chat
#  agent:
#    platform:
#      models:
#        deepseek:
#          api-key: ${DEEPSEEK_API_KEY}
  models:
    default-llm: qwen3:4b
  agent:
    platform:
      models:
        openai:
          custom:
            base-url: http://192.168.3.66:8000
            completions-path: /v3/chat/completions
            api-key: unused
            models: qwen3:4b
  observability:
    enabled: true
    service-name: WeatherAgent
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,metrics
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  langfuse:
    enabled: true
    endpoint: http://localhost:3000/api/public/otel
    public-key: ${LANGFUSE_PUBLIC_KEY}
    secret-key: ${LANGFUSE_SECRET_KEY}

openweather:
  api:
    key: ${OPENWEATHER_API_KEY}
