spring:
  application:
    name: embabel-java-agent-tutorial

embabel:
  models:
    default-llm: deepseek-chat
  agent:
    platform:
      models:
        deepseek-chat:
          model-name: deepseek-r1-qwen-7b
          base-url: http://192.168.3.66:8000/v3
          api-key: unused

openweather:
  api:
    key: ${OPENWEATHER_API_KEY}
